version: "3.9"
services:
  node-red:
    build: node-red
    networks:
      - node_red
    ports:
      - "1880:1880"
    environment:
      #GIT_BRANCH: ${GIT_BRANCH}
      #DB_USER: root
      #DB_PASS: pass
      #DB_HOST: db
      #DB_PORT: 3306
      #DB_DATABASE: demo
      
      # Miljøvariablen FLOWS fortæller Node-RED IDEet hvilket flow.json den skal åbne og gemme ændringer i ved deploy.
      FLOWS: "/data/flows.json"
      API_KEY: ${UDDANNELSESSTATISTIK_API_KEY}
      API_URL: ${UDDANNELSESSTATISTIK_API_URL}
      #UDDANNELSESSTATISTIK_WEBHOOK_URL: ${UDDANNELSESSTATISTIK_WEBHOOK_URL}
      CUSTOM_DATA_URL: ${CUSTOM_DATA_URL}

      #DEV_ENV: "true"
      
      # Bind mount fra codespace til den kørende containers /data.
      # Gør det muligt at deploye flowkode direkte fra IDE og bruge git til at comitte ændringerne til repo.
    volumes:
      - "./node-red/:/data" 
      
networks: 
  node_red:
    name: node_red
